### ISSUE TITLE
¿Meter el código de la isla dentro de municipios.csv?

### ISSUE THREAD

**Issue by inigoflores** [codeforspain/ds-organizacion-administrativa#2]
Viene de #1.

Como me ha quedado un poco larga la respuesta, he decido dividirla en varios issues.

> @fesja: Metería el código de la isla dentro de municipios.csv, asi no hace falta un archivo de municipios islas separado.

No lo veo claro.

Se trata de un caso de herencia de tablas con la siguiente estructura:

![](http://i.imgur.com/QNc1Abz.png)

Donde `Municipio Peninsular` no no añade nada nuevo sobre `Municipio`, con lo cual se puede obviar. 

En la herencia de tablas hay dos enfoques:
- **STI** (Single Table Inheritance): Una sola tabla con un montón de campos (lo que propone @fesja) para reflejar las propiedades comunes de la clase padre y de todos las clases hijas. No se recomienda por diversos motivos. [Three Reasons Why You Shouldn't Use Single Table Inheritance](http://rhnh.net/2010/07/02/3-reasons-why-you-should-not-use-single-table-inheritance)
- **CTI** (Class Table Inheritance): Una tabla para recoger las propiedades de la clase padre y una tabla por cada clase hija. 

![](http://i.imgur.com/saILxrq.png)

Por qué no usar STI:
- A medida que vayamos añadiendo clasificaciones administrativas (comarcas, partidos judiciales, etc.), se van a multiplicar el número de columnas.
- Van a a aparecer multitud de campos vacíos (p.e. municipios que no pertenecen a ninguna isla), con el consiguiente problema que esto genera.
- Cada vez que añadamos una columna, para reflejar este cambio hay que incrementar el número de versión del data package (siguiendo las recomendaciones Semantic Versioning 2). Tener que lidiar con múltiples versiones incrementa la complejidad.
- Cuando el data package se use para construir otro, o se use para automatizar la actualización de una base de datos, un número variable de columnas puede romper la compatibilidad (por ejemplo, si se usa `csvcut` o `csvjoin` especificando índices numéricos en vez del nombre de columna).

Otro argumento a favor de CTI es que pasar de CTI a STI es muy sencillo, y se consigue mediante un simple merge. Pero para realizar el paso inverso, hay que saber qué columnas pertenecen a cada tabla.

No estoy en contra ofrecer una tabla en formato STI, pero que no sea la opción por defecto o la única opción.  

Puedo incluir un nuevo recurso que sea construya a partir de otros, por ejemplo [data/municipios-sti.csv](https://github.com/codeforspain/ds-organizacion-administrativa/blob/master/data/municipios-sti.csv), que se genera mediante el siguiente comando:

```
`csvcut -c "municipio_id,isla_id" municipios_islas.csv | 
csvjoin -c municipio_id --left municipios.csv - | csvcut -C "3,4" |
csvjoin -c isla_id --left - islas.csv | csvcut -C "4,6,7" >
municipios-sti.csv`
```

 El único inconveniente de incluirlo en este dataset es que habría que ir modificando la versión semántica (al menos el `MINOR` y quizás el `MAJOR`) cada vez que se añada una nueva columna en este recurso, y así reflejar posibles cambios en compatibilidad con versiones anteriores.

Crear un dataset separado -p.e. `ds-organizacion-administrativa-sti-denorm` (un único recurso en formato sti y denormalizado haciendo un merge de todas las tablas)- eliminaría este problema, y facilitaría el merge con las geometrías.

**Comment by fesja** [comment]
Ver https://github.com/codeforspain/datos/issues/26, propongo una pausa en estos debates
