### ISSUE TITLE
¿Incluir las geometrías en este dataset?

### ISSUE THREAD

**Issue by inigoflores** [codeforspain/ds-organizacion-administrativa#3]
Viene de #1.

> @fesja: Por un tema de simplicidad y tener menos scripts, pongamos el listado y las geometrías en este repo. 

Tampoco veo este punto claro, y quizás es porque le estoy dando un enfoque más como desarrollador que como usuario final. Y esto no es necesariamente malo. 

Uno de los propósitos los paquetes de datos (data packages) es usarlos como si se trataran de paquetes software. De hecho, la especificación incorpora un campo llamado `dataDependencies` para lidiar con dependencias:

> `dataDependencies` - Object of prerequisite data packages on which this package depends in order to install. Follows same format as CommonJS Packages spec v1.1.Each dependency defines the lowest compatible `MAJOR[.MINOR[.PATCH]]` dependency versions (only one per MAJOR version) with which the package has been tested and is assured to work. The version may be a simple version string (see the version property for acceptable forms), or it may be an object group of dependencies which define a set of options, any one of which satisfies the dependency. The ordering of the group is significant and earlier entries have higher priority. Example:
> 
> ```
> "dataDependencies": {
>    "country-codes": "",
>    "unemployment": "2.1",
>    "geo-boundaries": {
>      "acmecorp-geo-boundaries": ["1.0", "2.0"],
>      "othercorp-geo-boundaries": "0.9.8",
>    },
> }
> ```

El propio ejemplo de arriba es bastante ilustrativo. Como dependencias define los paquetes `country-codes`, `unemployment`, `acmecorp-geo-boundaries` y `othercorp-geo-boundaries`. Observad que son paquetes muy especializados. Bloques básicos sobre los que se construye otro paquete de datos más complejo.

El empaquetar las geometrías en este mismo data package tiene los siguientes inconvenientes:
- **Incremento en el tamaño**: Si yo defino `ds-organizacion-administrativa` como dependencia porque necesito únicamente los códigos INE y nombres de municipios, el gestor de paquetes me va a instalar el paquete completo, incluyendo los cientos de megas de las geometrías.
- **Falta de independencia**: En vez de estas geometrías, puede ser que necesite usar un dataset de geometrías diferente. Pero esta configuración me obliga descargar todo el lote.
- **Complejidad en el código y obstáculo a la productividad**:  Por ejemplo, los scripts que estoy creando traen una función para regenerar automáticamente los archivos `datapackage.json`  cada vez que se ejecuta el script y a partir de unos datos de configuración. Hacer ambos scripts compatibles para que regeneren el `datapackage.json` es una trabajo complejo e innecesario, especialmente si están escritos en lenguajes diferentes.
  
  Por comodidad, he decido usar `PHP`. En el repo `ds-limites-administrativos` @jalbertoroman ha creado los scripts en Python. No creo que proceda de momento andar traduciendo scripts ni obligar a los colaboradores a usar un lenguaje de programación con el que a lo mejor no se sienten cómodos. Teniendo múltiples repos pequeños se incrementa la productividad y se facilita la colaboración.

Por lo que he visto hasta ahora, las geometrías siempre se ofrecen en datasets especializados, y el nombre suele empezar por (o contener) el texto `geo` ([algunos ejemplos](https://github.com/datasets?utf8=%E2%9C%93&query=geo)).

**Comment by fesja** [comment]
Ver https://github.com/codeforspain/datos/issues/26, propongo una pausa en estos debates
